sudo: required
services: 
  - docker 

before_install:
  - docker build -t test/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true test/docker-react npm run test

depoly:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-034362042068"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
